-- Create Menu Table
CREATE TABLE menu (
  id SERIAL PRIMARY KEY,
  type VARCHAR(1) NOT NULL,
  name VARCHAR(100) NOT NULL UNIQUE,
  image TEXT DEFAULT '',
  monday BOOLEAN DEFAULT FALSE,
  tuesday BOOLEAN DEFAULT FALSE,
  wednesday BOOLEAN DEFAULT FALSE,
  thursday BOOLEAN DEFAULT FALSE,
  friday BOOLEAN DEFAULT FALSE,
  saturday BOOLEAN DEFAULT FALSE,
  count INT DEFAULT 0
);

-- Create Members Table
CREATE TABLE members (
  id SERIAL PRIMARY KEY,
  index INT DEFAULT NULL,
  name VARCHAR(100) DEFAULT NULL,
  units INT DEFAULT 0
);

-- Create Orders Table
CREATE TABLE orders (
  id SERIAL PRIMARY KEY, 
  member_id INT REFERENCES members(id) ON DELETE SET NULL,
  date DATE NOT NULL,
  breakfast VARCHAR(100) NULL,
  b_received BOOLEAN NULL,
  lunch VARCHAR(100) NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  l_received BOOLEAN NULL
);
ALTER TABLE orders REPLICA IDENTITY FULL;