-- Create Menu Table
CREATE TABLE menu (
  id SERIAL PRIMARY KEY,
  menu_type VARCHAR(10) NOT NULL,
  name VARCHAR(100) NOT NULL,
  image TEXT,
  monday BOOLEAN DEFAULT FALSE,
  tuesday BOOLEAN DEFAULT FALSE,
  wednesday BOOLEAN DEFAULT FALSE,
  thursday BOOLEAN DEFAULT FALSE,
  friday BOOLEAN DEFAULT FALSE,
  saturday BOOLEAN DEFAULT FALSE,
  count INT DEFAULT 0
);

-- Create Members Table
CREATE TABLE members (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  monday BOOLEAN DEFAULT FALSE,
  tuesday BOOLEAN DEFAULT FALSE,
  wednesday BOOLEAN DEFAULT FALSE,
  thursday BOOLEAN DEFAULT FALSE,
  friday BOOLEAN DEFAULT FALSE,
  saturday BOOLEAN DEFAULT FALSE
);

-- Create Orders Table
CREATE TABLE orders (
  id SERIAL PRIMARY KEY, 
  member_id INT REFERENCES members(id),
  date DATE NOT NULL,
  breakfast VARCHAR(100),
  lunch VARCHAR(100),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
